os:
- linux
- osx
language: node_js
node_js:
- "10"
addons:
  apt:
    packages:
    - zsh
before_install:
- if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
- if [ $TRAVIS_OS_NAME = osx ]; then brew install zsh; fi
